### ISSUE TITLE
In WWW overview, `no_connection` should be highlighted

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized-web#1]
https://github.com/ytti/oxidized/issues/33

Hosts that don't work are not highlighted and thus are easy-ish to overlook. Please highlight them.

    XXX	YYY	default	no_connection	2014-08-12 07:54:08 UTC	config	update

**Comment by supertylerc** [comment]
@RichiH, in my current install, `no_connection` is highlighted.  See screenshot below.

![no-connection-highlight](https://cloud.githubusercontent.com/assets/4076147/12014493/abd20984-ace2-11e5-8825-00a28f87c5d4.PNG)

Can this issue be closed, or is it still a problem when running the latest `oxidized-web`?

**Comment by RichiH** [comment]
Looks good, can be closed.

Thanks,
Richard

Sent by mobile; excuse my brevity.
