### ISSUE TITLE
Escape HTML on config views

### ISSUE THREAD

**Issue by casdr** [ytti/oxidized-web#103]
Some configs have <removed> to remove things like the passwords. The problem is that these aren't escaped, so sometimes it breaks the view.

Maybe it's a good idea to escape the config?

**Comment by ytti** [comment]
Yeah sounds good, the HTML presenter part should have method which renders the config as HTML safe.

**Comment by pv2b** [comment]
I don't know if anything was done regarding this, but right now it seems oxidized-web escapes twice, so when looking at diffs for an XML config it looks like a mess.

**Comment by denngie** [comment]
yeah I noticed the same thing, in /node/version/diffs and /node/version/view the HTML source is:
`<div>! NAME: &amp;quot;Chassis&amp;quot;, DESCR: &amp;quot;Nexus5548 Chassis&amp;quot;</div>`
When it should be:
`<div>! NAME: &quot;Chassis&quot;, DESCR: &quot;Nexus5548 Chassis&quot;</div>`
It seems like it encodes the line twice, first `"` is replaced with `&quot;` and then `&quot;` is replaced with `&amp;quot;`
