### ISSUE TITLE
timestamps from UTC > CDT

### ISSUE THREAD

**Issue by shailigum** [ytti/oxidized-web#104]
I've seen the other posts in regards to the timestamps how they should be converting to browser time, but I can't seem to get this to work.

I have the server set to UTC and can confirm my Browser should be set to CDT.

Ideally i'd like to see it all in CDT, but am not very familiar with JS, so looking through the code didn't yield any results for me.

Can anyone point me in the right direction?  To get timestamps to update based on browser time, or change the system to do CDT altogether?

**Comment by danilopopeye** [comment]
@shailigum the function you should change is this `convertTime` here: [oxidized.js#L38-L59](https://github.com/ytti/oxidized-web/blob/55b16c3744af092970159d28afcd35abf99e0959/lib/oxidized/web/public/scripts/oxidized.js#L38-L59).
The most useful reference I could find is the issue #51.

**Comment by shailigum** [comment]
hmm..I am already running this in my code, looked through and found it earlier (referenced in #51 and etc).  

Is there something I should be doing other than just having the code in there?  Everything seems to be in place to me.

If I try the demo @oxidized.arahant.net I also see UTC instead of CDT, but i'm definitely CDT...

**Comment by danilopopeye** [comment]
This could be related to the javascript error I just fixed in #105, could you try my fix and see if it helps?

**Comment by shailigum** [comment]
perfect!  that worked, thank you.

**Comment by ytti** [comment]
Thanks @danilopopeye
