### ISSUE TITLE
Backup the vlan.dat file from (i.e.) cisco catalyst switches

### ISSUE THREAD

**Issue by sebisme** [ytti/oxidized-web#110]
I would like to save the vlan.dat file from Cisco Catalyst switches.
I found a way to send it to a predefined tftp server, but the problem is that the vlan.dat file is not stored in the git repo.

On ios.rb model file, i added the following code : 

```
cfg :telnet, :ssh do
# [...]
  if vars :get_vlan_dat
    pre_logout do
      send "copy vlan.dat tftp\n"
      send vars(:tftp_address)+"\n"
      send "\n"
    end
  end
end
```

This way, the vlan.dat file is sent to the tftp address :tftp_address... How could i do to copy that file to the git repo ?

Thanks !

**Comment by ytti** [comment]
Dunno why this was closed, but you could do ```more``` to print it on terminal.
