### ISSUE TITLE
Problem on versions with output git (pfsense)

### ISSUE THREAD

**Issue by pjust51** [ytti/oxidized-web#114]
Hi,

i use oxidized for backup configuration of my pfsense (v2.1.5) and it works, except for versions with git output :

Here are screenshots to illustrate the problem :

with the "configuration" button from first page, no problem :
https://www.noelshack.com/2017-04-1485185637-pfsense-1.png

with the versions button then configuration, xml tags are deleted and the backup from older versions is unusable :
https://image.noelshack.com/fichiers/2017/04/1485186495-pfsense-2.png

can you provide a solution or fix the problem ? thanks
==> https://github.com/ytti/oxidized/issues/671

**Comment by ytti** [comment]
ping @FlorianDoublet @supertylerc @MrRJ45

**Comment by pjust51** [comment]
any news ?

**Comment by wendelj** [comment]
Took a stab at fixing this.
https://github.com/wendelj/oxidized-web/commit/95d3742f9b9dfb1eb9159d2672b27010d6e8c065

**Comment by pjust51** [comment]
work like a charm ! big thanks

**Comment by ytti** [comment]
great work, can you submit PR?

**Comment by pjust51** [comment]
sorry I don't know how to do :(

**Comment by ytti** [comment]
That was for @wendelj
