### ISSUE TITLE
Missing dependency: json

### ISSUE THREAD

**Issue by abn** [ytti/oxidized-web#119]
The dependency list for oxidized-web seems to be missing `json` as used at https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web.rb#L1.

This was identified when debugging root cause for the following.
```
oxidized[26]: Oxidized crashed, crashfile written in /root/.config/oxidized/crash
oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration
/usr/lib/ruby/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:22:in `rescue in initialize': oxidized-web not found: sudo gem install oxidized-web - \ (Oxidized::OxidizedError)
          or disable web support by setting "rest: false" in your configuration
	from /usr/lib/ruby/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:19:in `initialize'
	from /usr/lib/ruby/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /usr/lib/ruby/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /usr/lib/ruby/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
	from /usr/bin/oxidized:22:in `load'
	from /usr/bin/oxidized:22:in `<main>'
```

**Comment by ytti** [comment]
Hey, ```json``` is standard library. To me it looks like you enabled REST/WWW, but you didn't install ```oxidized-web```.

**Comment by abn** [comment]
@ytti I did; but it seems its an distro issue. Using this under alpine. `oxidized-web` was installed. Here is the strace snippet that lead me to the missing `json` dep (sorry not familiar with the ruby ecosystem). Could it be a distro packaging issue?

```
open("/usr/lib/ruby/gems/2.3.0/gems/oxidized-web-0.8.0/lib/oxidized/web.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 8
fcntl(8, F_SETFD, FD_CLOEXEC)           = 0
fcntl(8, F_SETFL, O_RDONLY)             = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=725, ...}) = 0
fstat(8, {st_mode=S_IFREG|0644, st_size=725, ...}) = 0
ioctl(8, TIOCGWINSZ, 0x7ffd2286f180)    = -1 ENOTTY (Not a tty)
read(8, "require 'json'\n\nmodule Oxidized\n"..., 8192) = 725
read(8, "", 8192)                       = 0
close(8)                                = 0
lstat("/usr", {st_mode=S_IFDIR|0755, st_size=81, ...}) = 0
lstat("/usr/lib", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/ruby", {st_mode=S_IFDIR|0755, st_size=50, ...}) = 0
lstat("/usr/lib/ruby/gems", {st_mode=S_IFDIR|0755, st_size=19, ...}) = 0
lstat("/usr/lib/ruby/gems/2.3.0", {st_mode=S_IFDIR|0755, st_size=100, ...}) = 0
lstat("/usr/lib/ruby/gems/2.3.0/gems", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/ruby/gems/2.3.0/gems/oxidized-web-0.8.0", {st_mode=S_IFDIR|0755, st_size=155, ...}) = 0
lstat("/usr/lib/ruby/gems/2.3.0/gems/oxidized-web-0.8.0/lib", {st_mode=S_IFDIR|0755, st_size=22, ...}) = 0
lstat("/usr/lib/ruby/gems/2.3.0/gems/oxidized-web-0.8.0/lib/oxidized", {st_mode=S_IFDIR|0755, st_size=31, ...}) = 0
lstat("/usr/lib/ruby/gems/2.3.0/gems/oxidized-web-0.8.0/lib/oxidized/web.rb", {st_mode=S_IFREG|0644, st_size=725, ...}) = 0
open("/usr/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/json.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by ytti** [comment]
The traceback you show tells only about oxidized-web. Perhaps you installed it as root with 077 umask and now use can't read it?

**Comment by frankzhao** [comment]
Looks like `json` is included on debian but not on alpine. I tried this on alpine with a file test.rb

```
/ # cat test.rb 
require 'json'
/ # ruby test.rb 
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
    from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from test.rb:1:in `<main>'
```

But this runs fine on debian.

**Comment by abn** [comment]
Was running as root in a container. Should not have been a permission issue (at least not obviously). But I did manage to confirm that json does not seem to be present in alpine.

```
$ docker run --rm -it alpine sh
/ # apk --no-cache add ruby
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/10) Installing libffi (3.2.1-r2)
(2/10) Installing gdbm (1.12-r0)
(3/10) Installing gmp (6.1.1-r0)
(4/10) Installing ncurses-terminfo-base (6.0-r7)
(5/10) Installing ncurses-terminfo (6.0-r7)
(6/10) Installing ncurses-libs (6.0-r7)
(7/10) Installing readline (6.3.008-r4)
(8/10) Installing yaml (0.1.7-r0)
(9/10) Installing ruby-libs (2.3.3-r0)
(10/10) Installing ruby (2.3.3-r0)
Executing busybox-1.25.1-r0.trigger
OK: 26 MiB in 21 packages
/ # vi test.rb
/ # cat test.rb 
require 'json'
/ # ruby test.rb 
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from test.rb:1:in `<main>'
/ # 
```

**Comment by frankzhao** [comment]
Looks like alpine might have this seperated out into `ruby-json`
https://pkgs.alpinelinux.org/package/v3.3/main/x86/ruby-json

**Comment by ytti** [comment]
```
➜  find /usr/lib/ruby|grep -i json.rb
/usr/lib/ruby/2.2.0/json.rb
/usr/lib/ruby/2.3.0/json.rb
➜  
```

**Comment by abn** [comment]
Looks like it is a an alpine packaging oddity. Thanks @frankzhao @ytti. Will work around in my case by explicitly pulling it in.

**Comment by ytti** [comment]
I categorically refuse to believe they do not include standard library. There is json gem, but there is no need to install it.

**Comment by ytti** [comment]
Perhaps you've not installed ruby standard library?
➜  ~ dpkg -S /usr/lib/ruby/2.3.0/json.rb
libruby2.3:amd64: /usr/lib/ruby/2.3.0/json.rb
➜  ~

**Comment by abn** [comment]
https://pkgs.alpinelinux.org/contents?file=json.rb&path=%2Fusr%2Flib%2Fruby%2F2.3.0&name=&branch=&repo=&arch=

Looks like that is provided only via the `ruby-json` package.

**Comment by ytti** [comment]
I am speechless, this is standard library, no ruby software makes any attempt to depend on standard library. What could they possibly have thought removing file from standard library and put it on additional OS package, this is fundamentally broken.

**Comment by abn** [comment]
I could not find any documented reasons why that was done in the ruby case. However, I reckon it is safe to assume that the intention is to further the granularity of package components in order to allow for a minimalist foot print (as it is  one of their core objectives).

For anyone else that stumbles across this, the workaround/fix was to do one of the following as the issue lies in how the json library is packaged in alpine.
```sh
apk --no-cache add ruby-json
```
```sh
gem install json
```

**Comment by jadekler** [comment]
Good find. Wow. So annoying.

**Comment by laf** [comment]
I'm closing this down, it's documented in this issue and appears like it's just alpine linux that exhibits this rather than across the board.
