### ISSUE TITLE
Accessing the web interface

### ISSUE THREAD

**Issue by tylerapplebaum** [ytti/oxidized-web#12]
Please forgive my ignorance here.

I've got this on the same box as LibreNMS, and oxidized itself is working fine.

ruby      10519     root    9u  IPv4 59343430      0t0  TCP 127.0.0.1:8888 (LISTEN)

What is the default directory or port for oxidized-web?

**Comment by ytti** [comment]
It should answer in root directory of localhost (127.0.0.1) in port 8888. You can change this with 'rest' configuration directive:

rest: 127.0.0.0:4242

**Comment by tylerapplebaum** [comment]
Thank you. I'm an idiot...  changed 127.0.0.1 to the local server IP.
