### ISSUE TITLE
Bug in get diffs button when deployed under non-root directory

### ISSUE THREAD

**Issue by Mk-00** [ytti/oxidized-web#121]
Found a bug from https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/views/diffs.haml#L26

What would be the best way to fix this? 

`%form{action: "../../node/version/diffs?#{params}", method: 'post', role: 'form'}`
or
`%form{action: url_for("/node/version/diffs?#{params}"), method: 'post', role: 'form'}`

**Comment by ytti** [comment]
probably url_for
