### ISSUE TITLE
UTC/Localtime in /nodes 

### ISSUE THREAD

**Issue by kunwon1** [ytti/oxidized-web#125]
Hi! I have reviewed some old issues and I think this has come up a few times, I'm hoping I can help with closing it for good

I have oxidized monitoring 170 nodes. The first 100 nodes display in localtime on oxidized-web, no matter how they are displayed. To put that another way, when pagination is set to 50 nodes, pages 1 and 2 display in localtime, the remainder do not. When pagination is set to 250 nodes, the first 100 nodes show in localtime, the remainder do not, even though everything is displayed on a single page.

I have modified the oxidized core (e.g. to use tinytds through sequel and to ignore nodes with no name) but I have not touched oxidized-web

I am happy to do whatever is necessary to assist in solving this problem, please let me know if i can provide debugging information

**Comment by ytti** [comment]
I've not written this code and thus I have no familiarity with it So you'd need to either ping the original @author or just dive in to the code.
