### ISSUE TITLE
How to change default number of devices displayed from 50 to All?

### ISSUE THREAD

**Issue by tstasevych** [ytti/oxidized-web#127]
I would like to always show all results (150+) instead of paged view.

Thanks.

**Comment by bheum** [comment]
You can edit your nodes.haml file located somewhere like /var/lib/gems/2.1.0/gems/oxidized-web-0.8.0/lib/oxidized/web/views/nodes.haml
You can see your gem path using: `gem environment`
I added `"pageLength": -1,` to get a default of Show "All" entries

>"lengthMenu": [[50, 250, 500, -1], [50, 250, 500, "All"]],
"pageLength": -1,
columnDefs: [{
