### ISSUE TITLE
Backup file that contains xml

### ISSUE THREAD

**Issue by ivarhjulben** [ytti/oxidized-web#128]
Hi

I'm using Oxidized for config backup of our Innovaphone PBX's and the backup contains xml tags. It could be something like `pbx=<device hw="__SIP__"/>`.
This is not understood by the browser when versions are loaded.

I have so far fixed this by adding:
`require 'htmlentities'`
, after line https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/webapp.rb#L7

and adding:
`@data = HTMLEntities.new.encode(@data)`
, after line https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/webapp.rb#L177

Is it possible to include something like this in webapp.rb

Cheers,
Martin

**Comment by ytti** [comment]
This looks like a reasonable fix to me, submit a PR?

**Comment by ivarhjulben** [comment]
Thanks, I will submit a PR

And thanks for all the good work with Oxidized:-)

**Comment by ivarhjulben** [comment]
I have not done a pull request before and hope I did correct?
https://github.com/ytti/oxidized-web/pull/129

**Comment by ytti** [comment]
Looks good, thanks! You could have added 'Fixes #128' in commit body, and it would have autoclosed this once merged.
