### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Ynnot** [ytti/oxidized-web#139]
Hi ! 
I have a question. In stat mode, the "failure rate" is about the percentage of the config load or the percentage where Oxidized success to get the config ? 

Thank you.

**Comment by laf** [comment]
I think the failure rate is the percentage of devices that could be contacted. It might not still result in valid config backup but indicates the device responded correctly on telnet or ssh (I think)

**Comment by Ynnot** [comment]
Yes that's what I thought. 

Thank you i close !
