### ISSUE TITLE
Reload button does not work on Firefox ?

### ISSUE THREAD

**Issue by LemonLight** [ytti/oxidized-web#140]
Hi,

I recently noticed that the reload button doesn't work on Firefox but works perfectly on Chrome, Edge and IE.

Is it the same for you ?

Regards.

**Comment by danilopopeye** [comment]
@LemonLight can you open the console and see if any error appears?
Also, with version of Firefox are you using?

**Comment by LemonLight** [comment]
@danilopopeye Yes there are CSS and JS errors, do you want me to send you all of them ?
I'm running the v55.0.2

**Comment by LemonLight** [comment]
Poke @danilopopeye :)

**Comment by laf** [comment]
Just pastebin it here.

**Comment by LemonLight** [comment]
Here there is https://pastebin.com/kvkAbDyf

**Comment by danilopopeye** [comment]
hum, it seems that the code that changes the date from UTC to your browser tz is broken, so it prevents the bind to the reload button.

@LemonLight can you post the dates in the page where the problem is occurring?

**Comment by LemonLight** [comment]
Sorry by responding only now....
I am not sure to understand what you want ^_^
> can you post the dates in the page where the problem is occurring?

**Comment by LemonLight** [comment]
Well, it works good now (with FireFox 59)
