### ISSUE TITLE
Oxidized-web shows "&lt;secret hidden&gt;" on hidden passwords

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized-web#142]
Oxidized-web end is showing ```&lt;secret hidden&gt;``` instead of ```<secret hidden>``` for secret passwords.

Not sure how to fix this, but you can see an example of it here:

https://oxidized.arahant.net/node/version/view?node=192.168.88.233&group=&oid=47d8929215f1ecf0056ad8733e0dc0ea81a35770&date=2017-09-04%2018:34:39%20+0000&num=13

Then find "username Cisco".

Thanks,

Matt

**Comment by danilopopeye** [comment]
I think this was intended, or at least a side effect of this commit https://github.com/ytti/oxidized-web/commit/95d3742f9b9dfb1eb9159d2672b27010d6e8c065

**Comment by Mk-00** [comment]
I have noticed lot of issues in special character printing in oxidized web after upgrading from version 0.8.0 to 0.9.2, specially in double quotation marks in a switch config. I had to revert three commits to get the oxidized fully functional again after the upgrade.

First I reverted [this](https://github.com/ytti/oxidized-web/commit/094d50de4fb0c148289e3cdf3c5c4137a3138e99), [this](https://github.com/ytti/oxidized-web/commit/1959d709c337fe8445a9226661d52271b2d5ed8e) and [this](https://github.com/ytti/oxidized-web/commit/95d3742f9b9dfb1eb9159d2672b27010d6e8c065). After these, the diff view looks fine in oxidized web, but I still got broken configs to librenms which is fetching configs from oxidized. The last fix was to revert also [this commit](https://github.com/ytti/oxidized-web/commit/58736bb310cbe5b489a34f09490ea62cf50a6938).

**Comment by sliddjur** [comment]
Super annoying since all the vyatta/vyos config elements are with single quotes. Any fix coming for this?

**Comment by denngie** [comment]
I think this was solved in #151. Try to manually apply the changes or wait for 0.9.4 to be released

**Comment by mattie47** [comment]
@denngie  Have just tried manually and yes that fixes things. Will close this now.  👍 

However it doesn't appear to have fixed things when pulled into librenms (I've restarted oxidized with no change observed). @laf  should librenms/librenms#7382 be re-opened?
