### ISSUE TITLE
Problems with special characters in oxidized web versions 0.9.x

### ISSUE THREAD

**Issue by Mk-00** [ytti/oxidized-web#143]
I have noticed lot of issues in special character printing in oxidized web after upgrading from version 0.8.0 to 0.9.2, specially in double quotation marks in a switch config. I had to revert three commits to get the oxidized fully functional again after the upgrade.

First I reverted [this](https://github.com/ytti/oxidized-web/commit/094d50de4fb0c148289e3cdf3c5c4137a3138e99), [this](https://github.com/ytti/oxidized-web/commit/1959d709c337fe8445a9226661d52271b2d5ed8e) and [this](https://github.com/ytti/oxidized-web/commit/95d3742f9b9dfb1eb9159d2672b27010d6e8c065). After these, the diff view looks fine in oxidized web, but I still got broken configs to librenms which is fetching configs from oxidized. The last fix was to revert also [this commit](https://github.com/ytti/oxidized-web/commit/58736bb310cbe5b489a34f09490ea62cf50a6938).

**Comment by Mk-00** [comment]
There is also another issues regarding this problem but I decided to create a new one including all the commits that have affected to this issue. I have currently no time to debug this myself so decided to fix this in our environment by reverting couple of commits.

**Comment by laf** [comment]
@MK-00, please add your comments to #142 and close this.

**Comment by Mk-00** [comment]
Ok, I'll do this.
