### ISSUE TITLE
Oxidized-Web Config Differ : Not Shown

### ISSUE THREAD

**Issue by xssec** [ytti/oxidized-web#144]
Hi, Thank you for your great tools. I have some trouble to show config differ on web-gui like demo site: https://oxidized.arahant.net/node/version?node_full=192.168.88.231

And how to send alert to slack webhook, could you please give me the sample code?
![oxidized - 2017-09-27_1-11-47](https://user-images.githubusercontent.com/24645674/30876500-081fcf4c-a321-11e7-94c5-330b674dd5f9.png)

[config.txt](https://github.com/ytti/oxidized-web/files/1334406/config.txt)

Thank you...

**Comment by laf** [comment]
You're using file for output which doesn't support diffs. You need to switch to using git.

The readme has info on using slack: https://github.com/ytti/oxidized#hook-type-slackdiff

**Comment by xssec** [comment]
Hi Iaf,

is the format like this?
slack:
    type: slackdiff
    events: [post_store]
    token: https://hooks.slack.com/services/***********
    channel: "#network-changes"

**Comment by laf** [comment]
token should be just the token and not a url.

You also need to ensure the config is formatted as per the docs including indentations.

**Comment by xssec** [comment]
HI Laf,

Thank you so much. Now it running well.

**Comment by laf** [comment]
@xssec ace. Can you close this issue please.

**Comment by xssec** [comment]
Hi Iaf,

Upzzz... anw thx ya.
