### ISSUE TITLE
Increment version 

### ISSUE THREAD

**Issue by darkounet** [ytti/oxidized-web#15]
It is possible to upgrade the gem version ?

**Comment by ytti** [comment]
Not sure what you mean, I think Samer uploaded new gem today?

**Comment by darkounet** [comment]
the 0.3.0 gem doesn't include the #7 PR

**Comment by ytti** [comment]
Right, @nopedial can release 0.4.0 as it seems important to you

**Comment by nopedial** [comment]
Updated

**Comment by darkounet** [comment]
you made my day :)
