### ISSUE TITLE
webpage not display properly with nginx sub-location directive

### ISSUE THREAD

**Issue by davama** [ytti/oxidized-web#153]
Hello,

Not sure if oxidized issue or oxidized-web or even nginx for that matter...
I can make oxidized-web appear fine with the following configurations (all web features work)

(https://\<FQDN\>/nodes)
/etc/nginx/nginx.conf 
```
...
...
    server {
...
... 
# oxidized-web is in the root location of the site
location / {
	auth_ldap "WHQ LDAP Authentication";
	auth_ldap_servers ldap_local;
	proxy_pass http://127.0.0.1:9002;
}
    }
```

~/.config/oxidized/conf
`rest: 127.0.0.1:9002`

But when i make the following changes it does not appear properly

(https://\<FQDN\>/oxidized/nodes)
/etc/nginx/nginx.conf
```
....
location /oxidized {
	auth_ldap "WHQ LDAP Authentication";
	auth_ldap_servers ldap_local;
	proxy_pass http://127.0.0.1:9002/oxidized;
}
```
~/.config/oxidized/conf
`rest: 127.0.0.1:9002/oxidized`

We are hosting other web services. That is why we are using multiple locations.
Hope this makes sense.
Please let me know if need more information.

Ussing latest and greatest :smiley:  
CentOS Linux release 7.4.1708 (Core) 
Kernel: 3.10.0-693.11.6.el7.x86_64
oxidized-0.21.0
oxidized-script-0.5.0
oxidized-web-0.9.3

Thanks!
dave

**Comment by davama** [comment]
Nice and pretty
![Nice and pretty](https://i.imgur.com/JmdrXt9.png)


Not so pretty ... :(
![Not so pretty](https://i.imgur.com/YemJlQh.png)

**Comment by laf** [comment]
Not sure this is an oxidized issue. We do the same with apache with no issues. 

I’ll check our config and reply. Remind me in a few days if I’ve forgot.

**Comment by davama** [comment]
Thank you for replying @laf . I'll be sure to remind you :smile: 

Update: 
I was curious if it was some type of timer delay that cause oxidzed-web to not display properly, since in oxidized we have +1000 clients.
As a test i dropped the number of clients in the oxidized DB to 50 with no change :disappointed: 

oxidized-web still appears not very pretty.

**Comment by laf** [comment]
Oxidized:

`rest: 0.0.0.0:8443/oxidized`

Apache:
```
ProxyPassReverse        /oxidized/                      http://x.x.x.x:8443/oxidized/
ProxyPass               /oxidized/                      http://x.x.x.x:8443/oxidized/
```

So, try a `/` on the end of `/oxidized` in your config.

**Comment by davama** [comment]
@laf thank you for the tip

I realized that i have a `root` directive in my cgit.conf file which is not in the cgit location but in the `server` block... that was what was causing the issues.... :(

/etc/nginx/locations/cgit.conf 
```
location ~* ^.+\.(css|png|ico)$ {
	root /usr/share/cgit;
	expires 30d;
}
location /cgit/ {
	#root /usr/share/cgit;
	auth_ldap "WHQ LDAP Authentication";
 	auth_ldap_servers ldap_local;
...
...
}
```

For some reason i cannot get cgit to respect the `root` if it's inside the `location cgit` block.
This is outside oxidzed so i'll close.
Thank you for the kind support!

dave
