### ISSUE TITLE
Juniper Config signs are interpreted wrong

### ISSUE THREAD

**Issue by tobzsc** [ytti/oxidized-web#155]
When I am looking at the configuration versions several signs are interpreted wrong:

See:

`groups {
     disabled {
        interfaces {
            &lt;ge-0/0/*&gt; {
                disable;
            }
            &lt;xe-0/1/*&gt; {
                disable;
            }
            &lt;ge-0/1/*&gt; {
                disable;
            }
        }
    }
}`

Looks like some HTML special signs are interpreted wrong. The same configuration is shown correctly under the default page where I can fetch the config. This is just happening on the versions page.

**Comment by laf** [comment]
Duplicate https://github.com/ytti/oxidized-web/issues/132
