### ISSUE TITLE
blank hostname

### ISSUE THREAD

**Issue by rsaeba** [ytti/oxidized-web#157]
Hi,

Thanks for Oxidized, great project !
Now, I've some issues with some fortinet hosts.
Backups are correct, but on the oxidized web-ui, some rows are blank in the hostname column.
![blankhostnames](https://user-images.githubusercontent.com/37365413/37396504-5f44476c-2779-11e8-8ed1-1ec4bbbe5612.jpg)
Can you help me please ?

Thanks a lot !

rsaeba

**Comment by yzguy** [comment]
What version of oxidized-web are you running? The latest release does not even have "Hostname" anymore as a column.

**Comment by laf** [comment]
@yzguy Well spotted :)

@rsaeba Please update oxidized, oxidized-web and oxidized-script to the latest version and try again. If you still have the issue please comment back here with the versions you are running and we can re-open this.

**Comment by rsaeba** [comment]
OK. The hostname was not filled because hosts were not added before in devices list.
