### ISSUE TITLE
Timezone for lastUpdate

### ISSUE THREAD

**Issue by darkounet** [ytti/oxidized-web#16]
It is possible to add a field to specify the timezone for the Last Update ?

**Comment by ytti** [comment]
It's right now UTC, which I feel is the correct solution. The moment you have devices in over 1 TZ, nothing else seems sensible.

But I'd be happy to accept pull request for javascript/UI based mangling of timestamp, so browser could change it, and perhaps use cookie to in next session.
I don't think we should have option to have other than UTC in data structures, presentation is ok.

**Comment by supertylerc** [comment]
@darkounet @ytti, #51 automatically converts the timezone in the web UI.  It relies on the browser reporting the correct timezone and the server being set to UTC.
