### ISSUE TITLE
Haml precompiled_method_return_value

### ISSUE THREAD

**Issue by Lukiko** [ytti/oxidized-web#168]
I have oxidized and oxidized-web running on CentOS 7.1. Everything appears to be working just fine, but whenever I open or click anything in the Web UI I get this warning 3 times:

![oxidized_haml_warning](https://user-images.githubusercontent.com/12966742/40812029-bf7bb938-6501-11e8-9f55-8687a96a571d.PNG)

I'm running Ruby 2.5.1 and tried updating haml to 5.0.4 to see if it corrected the issue, but I may have done it incorrectly. I tried a fresh install with Ruby 2.4.1 as well, but I get the same warning.

Appreciate any help!

**Comment by wk** [comment]
Since the currently released gem depends on the older version, it is likely that after upgrading haml, both versions are installed and oxidized makes use of the older one (validate with `gem list | grep haml` as the oxidized user - are there two versions listed?).

If that's the case - at this point, it will be necessary to either force gem to uninstall the older version (breaking the dependency chain), or to build your own oxidized-web gem from the git master, as this has already been corrected in #162.

@ytti this might call for cutting a release of oxidized-web here, as more and more distributions ship with modern rubies, triggering this issue.

**Comment by Lukiko** [comment]
I saw that this had been corrected in [162](https://github.com/ytti/oxidized-web/pull/162), but I was receiving the warning on a fresh install (of CentOS and oxidized) using haml 4.0.7 that comes with the gem.

I have no problem using an older version of Ruby as well to avoid this issue. What version would you recommend? Or should I build the oxidized-web gem from the git master?

Thanks again for your help, and I apologize for my ignorance here. Your hard work is appreciated!

**Comment by wk** [comment]
After installing `oxidized` and `oxidized-web`, it should be possible to do `gem uninstall haml --version <your version 4.x>`. This will complain about breaking dependencies and require confirmation, but ultimately succeed. After this, you should be able to install version 5 of haml. 

This should result in a working configuration, sans the warnings.

**Comment by Lukiko** [comment]
Building directly from git solved the issues. Thank you for that. I rebuilt the server again this morning to clean up it and realized there was a new release. Unfortunately, the new release this morning does not appear to work.

[oxidized@Netmon01 oxidized]$ oxidized
I, [2018-06-03T11:27:38.207698 #60168]  INFO -- : Oxidized starting, running as pid 60168
I, [2018-06-03T11:27:38.208756 #60168]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2018-06-03T11:27:38.345833 #60168]  INFO -- : lib/oxidized/nodes.rb: Loaded 3 nodes
F, [2018-06-03T11:27:38.348967 #60168] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/cra                                                  sh
oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration

**Output from the crash log:**

--------------------------------------------------
2018-06-03 15:27:38 UTC
oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration [Oxidized::OxidizedError]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:22:in `rescue in initialize'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:19:in `initialize'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/bin/oxidized:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.1/bin/oxidized:23:in `load'
/usr/local/rvm/gems/ruby-2.5.1/bin/oxidized:23:in `<main>'
/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
--------------------------------------------------

oxidized-web is in fact installed (0.10.1). I tried re-installing anyways.
