### ISSUE TITLE
oxidized-web not found

### ISSUE THREAD

**Issue by Lukiko** [ytti/oxidized-web#169]
Fresh install with the new releases and oxidized-web does not appear to be working. I tried to install using bundler but received an error when oxidized-web required oxidized 0.21.0.

gem install oxidized-web is also installing oxidized 0.21.0.

[oxidized@Netmon01 oxidized]$ oxidized
I, [2018-06-03T11:42:56.227473 #8109]  INFO -- : Oxidized starting, running as pid 8109
I, [2018-06-03T11:42:56.229390 #8109]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2018-06-03T11:42:56.380593 #8109]  INFO -- : lib/oxidized/nodes.rb: Loaded 3 nodes
F, [2018-06-03T11:42:56.382533 #8109] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration

_output from crash log:_ 

2018-06-03 15:42:56 UTC
oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration [Oxidized::OxidizedError]

/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:22:in `rescue in initialize'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:19:in `initialize'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.22.0/bin/oxidized:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.5.1/bin/oxidized:23:in `load'
/usr/local/rvm/gems/ruby-2.5.1/bin/oxidized:23:in `<main>'
/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by ytti** [comment]
I relaxed the oxidized-web requirements in 0.10.2 unsure if it helps, i mean it should've just installed 0.21.0 and be happy with it, undesirable situation but non catastrophic.

**Comment by Lukiko** [comment]
Uninstalled and re-installed. Appears to be working again. Thank you!

**Comment by ytti** [comment]
Awesome, my thanks and apologies.
