### ISSUE TITLE
Unable to install oxidized-web gem

### ISSUE THREAD

**Issue by hunnymonster** [ytti/oxidized-web#171]
Hi all - up until yesterday all was working fine... in trying to fix, I've completely uninstalled oxidized, oxidized-script & oxidized-web and reinstalled... 

oxidized & oxidized-script install just fine.

oxidized-web no so much.

Get the same issue with ruby 2.3 & 2.5...

`root@####:~# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

`root@####:~# gem install -V oxidized-web
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=oxidized-web
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/oxidized-web-0.11.1.gemspec.rz
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=charlock_holmes,emk-sinatra-url-for,haml,htmlentities,json,oxidized,puma,rack-test,sass,sinatra,sinatra-contrib
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=temple,tilt
200 OK`

Tells me to look in the charlock_holmes log that doesn't help a whole lot...

`Building has failed. See above output for more information on the failure.
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/charlock_holmes-0.7.6/mkmf.log

extconf failed, exit code 1`

**Comment by wk** [comment]
Install `libicu` and `g++` system packages prior to installing oxidized-web so that charlock_holmes can build correctly.

**Comment by hunnymonster** [comment]
Thanks, but they're already present and apparently up to date:

`root@netmon:~# apt install libicu-dev g++
Reading package lists... Done
Building dependency tree
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
libicu-dev is already the newest version (55.1-7ubuntu0.4).`

**Comment by wk** [comment]
The installation instructions have been re-validated and updated to reflect this in ytti/oxidized#1383
