### ISSUE TITLE
rb-notify version 0.10.0 needs Ruby 2.2.2 or newer 

### ISSUE THREAD

**Issue by jasgrider** [ytti/oxidized-web#179]
Trying a new fresh install on a CentOS7 box and got this error when installing oxidized-web:

```bash
> gem install oxidized-web
ERROR:  Error installing oxidized-web:
	rb-inotify requires Ruby version >= 2.2.
```
I searched for the previous version of rb-inotify and installed it, then successfully installed oxidized-web.

```bash
> gem search -a rb-inotify

*** REMOTE GEMS ***

rb-inotify (0.10.0, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.3, 0.8.2, 0.8.1, 0.8.0, 0.7.2, 0.7.1, 0.7.0, 0.6.0, 0.5.1, 0.5.0, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0)
```

```bash
> gem install rb-inotify -v 0.9.10
Fetching: rb-inotify-0.9.10.gem (100%)
Successfully installed rb-inotify-0.9.10
Parsing documentation for rb-inotify-0.9.10
Installing ri documentation for rb-inotify-0.9.10
1 gem installed
```

```bash
> gem install oxidized-web 
<snip all that output>
7 gems installed
>
```

I assume that the reference for rb-inotify needs to be updated to lock in 0.9.10 for now similarly to #149 & #165. 

I'll try to do a pull request for it to get that updated but I wanted to put an issue out there for anybody searching for this exact error.

**Comment by wk** [comment]
While oxidized aims to support 2.0+ out of the box, it is no longer recommended to run it on rubies older than 2.2.6. As CentOS is expected to release version 8 with a modern modern ruby interpreter within the next few months (currently in beta), it's likely that the supported version will be bumped to 2.4+ in the near future.

You're welcome to submit a (tested) version lock, and @ytti might have an opportunity to do another release before the version bump takes place.

**Comment by wk** [comment]
Official support has been bumped to 2.3, closing this.
