### ISSUE TITLE
REST API function to add new device(s) to Oxidized 

### ISSUE THREAD

**Issue by netops2devops** [ytti/oxidized-web#188]
Greetings,

I'm trying to figure out if there's a way to do HTTP POST requests to oxidized-web to add new device(s) using the REST API. I currently do not see that functionality available over web interface. I am not a ruby programmer so in case if this is already available somewhere within webapp.rb then kindly guide me to the right URL to which I can make POST requests. Any help or pointers are appreciated. 

Thank you!

**Comment by ytti** [comment]
There is not, we don't have any state stored between oxidized restarts currently, so adding this type of support would require first adding state of the devices.

**Comment by netops2devops** [comment]
Thanks for your response. I'll close this issue now.
