### ISSUE TITLE
Could we find last backup status with ruby script ?

### ISSUE THREAD

**Issue by Niolith** [ytti/oxidized-web#192]
Hello, 

I don't know if it's the good section to ask this, but i'm wondering if it's possible to determine in ruby script the last backup status of each device in our Oxidized ?

I check with Oxidized-script if it's possible to do that, but I didn't find anything interesting.

Thank you,

**Comment by BapRx** [comment]
Hi, you get that info with a simple ruby script:
```
#!/usr/bin/env ruby

require 'open-uri'
require 'json'

begin
 json = JSON.parse(open("http://localhost:8888/nodes.json").read)
rescue
  puts 'Unable to connect'
  exit 2
end

json.each do |node|
  if not node['last'].nil?
    puts node['name'] + ' last update time: ' + node['last']['end']
  end
end
```
