### ISSUE TITLE
Problems with performance when gits have a large number of versions

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized-web#212]
Oxidized-web 0.13.1
oxidized (0.28.0)

Pulling a revision via the web interface can take up to 10 minutes, a thing noticeable in LibreNMS as well.

Doing git gc on bare gits does not seem to improve performance.

I havent been able to see noticeable difference between a git with 83k versions and one with 23k versions. It still takes over 10 minutes.  

Clicking on the versions button makes the whole interface freeze until the version is retrieved. 

Config collection does not seem affected. Hooks are being done, all good there.

Would need some help debugging.

**Comment by MarcHagen** [comment]
Still issues with oxidized 0.29.1 + Oxidized-web 0.13.1 (there hasnt been any updates)
Setting `history_size: 4` helps a bit, but not much.

**Comment by robertcheramy** [comment]
The issue is in oxidized.
You need to run `git gc` on your oxidized git repo.
I will document this / see issue https://github.com/ytti/oxidized/issues/3121
