### ISSUE TITLE
New tag request

### ISSUE THREAD

**Issue by miff2000** [ytti/oxidized-web#213]
Please could I ask for a new tag to be released for this?

I would like to use the changes in https://github.com/ytti/oxidized-web/pull/206 in the Docker image for Oxidized, but it presently pulls in an older version of the library `oxidized/web` library which doesn't include it

Thanks :)

**Comment by wk** [comment]
@ytti I don't think there are any blockers to cutting a release

**Comment by fbouynot** [comment]
Hi, would it still be possible to tag this please?
It would make integration with LibreNMS faster on some tasks.

**Comment by robertcheramy** [comment]
Release 0.14 is planed. Closing this issue.
