### ISSUE TITLE
Why no command support via oxidized-web?

### ISSUE THREAD

**Issue by miff2000** [ytti/oxidized-web#214]
I'm looking for a way to be able to execute commands against devices using the API, like I would using the `oxs` command provided in https://github.com/ytti/oxidized-script. It doesn't seem to be possible though.

Am I correct in my understanding here, or is there a method of running commands?

Assuming I am correct, would you be willing to accept a PR to extend `oxidized-web` to add an endpoint for it?
I'm thinking to add a POST to `/node/command` with argument `node`, like:

```
POST /node/command?node=<node-fqdn>
```

**Comment by ytti** [comment]
I would probably accept, I'm not too sensitive on oxidized-web changes. But oxidized proper changes should be cleanish.

**Comment by miff2000** [comment]
I'll aim to get something built and tested then :) Thansk!

**Comment by miff2000** [comment]
One of my colleagues has had the time to put a PR in for this here: https://github.com/ytti/oxidized-web/pull/216
