### ISSUE TITLE
Sync status: no_connection 

### ISSUE THREAD

**Issue by Bencamelas** [ytti/oxidized-web#218]
Hello, checking the rust configuration I get the following information, however the router.db file already has the device information, this is because

![image](https://user-images.githubusercontent.com/77454191/104619412-d4f87f00-565b-11eb-974d-fba58ad38342.png)

I do not know if it is due to a bad configuration of the snmp, although I do not believe that everything else if you let me observe it

**Comment by robertcheramy** [comment]
Not an oxidized-web issue. Check with hpe.
