### ISSUE TITLE
Unable to run oxidized with web

### ISSUE THREAD

**Issue by amshikov** [ytti/oxidized-web#219]
Hello!

I have fresh install of oxidized from ports on FreeBSD 12.2-RELEASE. I'm unable to run it with web, oxidized throws an error:

I, [2021-02-06T16:24:32.543285 #9425]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes

F, [2021-02-06T16:24:32.557666 #9425] FATAL -- : Oxidized crashed, crashfile written in /var/db/oxidized/.config/oxidized/crash
oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration
Traceback (most recent call last):
        8: from /usr/local/bin/oxidized:23:in `<main>'
        7: from /usr/local/bin/oxidized:23:in `load'
        6: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        5: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        4: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        3: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        2: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:21:in `initialize'
        1: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- oxidized/web (LoadError)
        14: from /usr/local/bin/oxidized:23:in `<main>'
        13: from /usr/local/bin/oxidized:23:in `load'
        12: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        11: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        10: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         9: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         8: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:21:in `initialize'
         7: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:34:in `require'
         6: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
         5: from /usr/local/lib/ruby/site_ruby/2.7/rubygems.rb:218:in `try_activate'
         4: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1417:in `activate'
         3: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1435:in `activate_dependencies'
         2: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1435:in `each'
         1: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1446:in `block in activate_dependencies'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/dependency.rb:313:in `to_specs': Could not find 'puma' (~> 3.11, >= 3.11.4) - did find: [puma-5.1.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/var/db/oxidized/.gem/ruby/2.7:/usr/local/lib/ruby/gems/2.7', execute `gem env` for more information
        15: from /usr/local/bin/oxidized:23:in `<main>'
        14: from /usr/local/bin/oxidized:23:in `load'
        13: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        12: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        11: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        10: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
         9: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:21:in `initialize'
         8: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:34:in `require'
         7: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
         6: from /usr/local/lib/ruby/site_ruby/2.7/rubygems.rb:217:in `try_activate'
         5: from /usr/local/lib/ruby/site_ruby/2.7/rubygems.rb:224:in `rescue in try_activate'
         4: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1417:in `activate'
         3: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1435:in `activate_dependencies'
         2: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1435:in `each'
         1: from /usr/local/lib/ruby/site_ruby/2.7/rubygems/specification.rb:1446:in `block in activate_dependencies'
/usr/local/lib/ruby/site_ruby/2.7/rubygems/dependency.rb:313:in `to_specs': Could not find 'puma' (~> 3.11, >= 3.11.4) - did find: [puma-5.1.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/var/db/oxidized/.gem/ruby/2.7:/usr/local/lib/ruby/gems/2.7', execute `gem env` for more information
        7: from /usr/local/bin/oxidized:23:in `<main>'
        6: from /usr/local/bin/oxidized:23:in `load'
        5: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        4: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        3: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        2: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        1: from /usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:20:in `initialize'
/usr/local/lib/ruby/gems/2.7/gems/oxidized-0.28.0/lib/oxidized/core.rb:23:in `rescue in initialize': oxidized-web not found: sudo gem install oxidized-web - \\ (Oxidized::OxidizedError)
          or disable web support by setting "rest: false" in your configuration

But all gems are in place:
`> gem list

*** LOCAL GEMS ***

asetus (0.3.0)
bcrypt_pbkdf (1.0.1)
charlock_holmes (0.7.7)
ed25519 (1.2.4)
emk-sinatra-url-for (0.2.1)
ffi (1.14.2)
haml (5.0.4)
htmlentities (4.3.4)
json (2.3.1)
json_pure (2.3.1)
multi_json (1.15.0)
mustermann (1.1.1)
net-ssh (5.2.0)
net-telnet (0.2.0)
nio4r (2.5.4)
oxidized (0.28.0)
oxidized-web (0.13.1)
puma (5.1.1)
rack (2.2.3, 1.6.13)
rack-protection (2.1.0, 1.5.5)
rack-test (1.1.0)
rb-fsevent (0.10.3)
rb-inotify (0.10.1)
ruby2_keywords (0.0.4)
rugged (1.0.1)
sass (3.7.4)
sass-listen (4.0.0)
sinatra (2.1.0, 1.4.8)
sinatra-contrib (1.4.7)
slop (4.6.2)
temple (0.8.2)
tilt (2.0.9)
`

Please advice! Thank you.

**Comment by tuxis-ie** [comment]
I just fixed this (on Debian Buster) by uninstalling oxidized and deps, and then removing the /root/.gem directory and reinstall oxidized. For me, an upgrade of Debian changed some Ruby versions and I think because of caching in the .gem directory, gem kept reinstalling an incorrect version of the gem (but I'm no Ruby expert).

**Comment by robertcheramy** [comment]
Install issue
