### ISSUE TITLE
show when a line was inserted in oxidized-web

### ISSUE THREAD

**Issue by spinoshi** [ytti/oxidized-web#229]
Hello, 

would it be possible to show the commit that inserted a specific line of configuration in oxidized-web? 
Something like the blame in gitlab. 
I am asking because the diff functionality in oxidized-web is way more usable than the one in gitlab, but this additional functionality would be very useful. 
I am migrating from rancid to oxidized and this is present in Rancid (named annotate)

Thanks for your help! 
Simone

**Comment by robertcheramy** [comment]
As no one proposed a PR for this in years, I close the issue. Use git blame.
