### ISSUE TITLE
oxidized.arahant.net domain expired

### ISSUE THREAD

**Issue by Firefishy** [ytti/oxidized-web#230]
On visiting http://oxidized.arahant.net/ it appears to be have taken over by a domain squatter.

The `arahant.net` domain appears to have expired a few days ago.

**Comment by Firefishy** [comment]
Linked: https://github.com/ytti/oxidized-web/issues/181

**Comment by robertcheramy** [comment]
Fixed with 2224711415a8410f505109cba3c67aea4569e1d8
