### ISSUE TITLE
Wrong number of Arguments (given 0, expected 1+) 

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized-web#235]
Good day,
My oxidized git versioning has stopped working. Ruby 2.7.0 and Oxidized 2.7.0 and Oxidized web 0.13.1. The install is from last year in June so the git.rb is already set to walker.push(repo.head.target.oid). The error I'm getting on the web interface is:
  ArgumentError at /node/version
  wrong number of arguments (given 0, expected 1+)
  file: versions.haml
  location: count
  line: 24
Any pointers or hints will be very appreciated!

**Comment by tokarenkos** [comment]
I have oxidized 0.29.0 and some problem with web interface. When I click on "version"

**Comment by quotengrote** [comment]
see also herer: https://github.com/ytti/oxidized/issues/2760

**Comment by robertcheramy** [comment]
Can't reproduce, old issue => closed. Open a new issue if the problem stil persists.
