### ISSUE TITLE
puma6 no longer supports Rack::Handler.get(:puma)

### ISSUE THREAD

**Issue by nickhilliard** [ytti/oxidized-web#238]
oxidized-web will run happily with any version of puma up to  5.6.5. However ```Rack::Handler.get(:puma)```  no longer works as a construct in puma 6.x.

This will need to be addressed at the following locations:

https://github.com/ytti/oxidized-web/blob/84c5fd8ea4b6db4a306f7cda489fed4619a85aa8/lib/oxidized/web.rb#L8
https://github.com/ytti/oxidized-web/blob/84c5fd8ea4b6db4a306f7cda489fed4619a85aa8/lib/oxidized/web.rb#L29

**Comment by robertcheramy** [comment]
Closed by #239
