### ISSUE TITLE
Hiding enable password (vars)

### ISSUE THREAD

**Issue by jthunt** [ytti/oxidized-web#24]
Just a suggestion, but the enable password should probably be hidden on the web frontend.

**Comment by ytti** [comment]
Or perhaps it should have access levels, so that not everyone can pull node information.

**Comment by etern4ever** [comment]
That would work.  Just need a way to identify users then.   Currently, I am thinking about binding oxidized-web to localhost and using nginx with ldap to support user login then proxy the connection to localhost.

Something built in would be better.
