### ISSUE TITLE
Expose log file via web UI

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized-web#3]
This could be as simple as offering a page that loads the log file in full and displays it via www.

If the web UI is the preferred way to interact with oxi, it should be possible to look up any errors/warnings in there, as well.

**Comment by tobiasa1** [comment]
I like the idea to allow both syslog and file simultaneously.

**Comment by ytti** [comment]
Yeah we need to return file logging support. Especially for dockerized installs it's more prudent to log to file (STDOUT).

**Comment by supertylerc** [comment]
Can the discussion of logging to a file be moved to [ytti/oxidized](https://github.com/ytti/oxidized)?

Once that is implemented, I can look into displaying the logs in the web UI.
