### ISSUE TITLE
Relative URI

### ISSUE THREAD

**Issue by nickhilliard** [ytti/oxidized-web#32]
the web interface is hardcoded to be located at /

It would be v. handy to have the base URI as a configurable option, because this would allow integration into an existing web site framework using proxying.

**Comment by ytti** [comment]
I don't think it actually is.
https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web.rb#L11
https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web.rb#L21

The routes should be relative to that URI.

**Comment by supertylerc** [comment]
@nickhilliard, is this still an issue?  If so, could ou give an example web framework using proxying that I could use to replicate the issue?

Thanks!

**Comment by nickhilliard** [comment]
nope, not an issue. oxidized config as follows:

```
rest: 10.x.x.x:8888/oxidized
```
Apache config:

```
ProxyPass               /configcm/              http://10.x.x.x:8888/oxidized/
ProxyPassReverse        /configcm/              http://10.x.x.x:8888/oxidized/
```
works great.
