### ISSUE TITLE
Ability for "Search in confs" to support regex searches within configurations

### ISSUE THREAD

**Issue by gbbromley** [ytti/oxidized-web#33]
Currently when using the "Search in confs" button the search terms doesnt appear to support regex. So a search for ^ip http server will return no results, but ip http server returns results for ip http server and also no ip http server.

This limits the usefulness of the search in confs function to generalistic searches, rather than specific searches to identify defective devices.

Coudl we get a regex compatible search field some time?

**Comment by supertylerc** [comment]
Hi, @gbbromley.  Not sure if this is something for which you are still looking, but #50 implements this feature.

Thanks!
