### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by masonke** [ytti/oxidized-web#37]
I must be blind, were is the installation, config and startup information?

**Comment by ytti** [comment]
Documentation is lacking for sure.

Have you read the README.md at https://github.com/ytti/oxidized

**Comment by masonke** [comment]
I had read it, but it looks like enabling REST also enables the web page?

~KEM

**Comment by masonke** [comment]
Total noob question. Where are the actual configs stored when using Output: Git?  When I used File, the actual config files were available. Is it the same with GIT?

My repo is locate on /data/oxidized/devices.git, the source is Librenms.

Any ideas?

/etc/oxidized/config
model: ios
interval: 3600
log: /data/oxidized/log
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 10.1.1.8:8888
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false

output:
  default: git
  git:
    user: Oxidized
    email: Oxidized@m <mailto:Oxidized@vistaprint.com>ycompany.com
    repo: "/data/oxidized/devices.git"


source:
    default: http
    debug: true
    http:
      url: http://librenms.mycompany.net/api/v0/oxidized <http://librenms.mycompany.net/api/v0/oxidized>
      scheme: http
      delimiter: !ruby/regexp /:/
      map:
        name: hostname
        model: os
      headers:
        X-Auth-Token: ‘123456789abcdef'


~KEM

**Comment by ytti** [comment]
The actual configs should be in /data/oxidized/devices.git as git repo, you can check it out somewhere

```
# git clone /data/oxidized/devices.git /tmp/configs
````


and update
```
# cd /tmp/configs
# git pull
```

And yes, enabling web page is done by enabling rest.

**Comment by supertylerc** [comment]
Can this be closed?  I'm looking to contribute, and closing old issues that are resolved would help me identify what still needs work.

Thanks!

**Comment by supertylerc** [comment]
@masonke, any update on whether or not this can be closed?

**Comment by masonke** [comment]
Please close.

I thought I had already, my apologies
~KEM
