### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by sts** [ytti/oxidized-web#4]
I was playing with the frontend code a bit and pulled in bootstrapcss. Thats what I came up with, I wonder what you guys think about it. It features a realtime search as well.

![image](https://cloud.githubusercontent.com/assets/204585/4483079/193cf1f8-49ae-11e4-8e84-30c41b515f6b.png)

**Comment by sts** [comment]
;-)

**Comment by nopedial** [comment]
0.2.0 is out on rubygems with the new UI
