### ISSUE TITLE
Redesign Migration Page

### ISSUE THREAD

**Issue by supertylerc** [ytti/oxidized-web#58]
The UI for the migration page does not currently fit with the UI of the rest of the web interface.  It should be updated to match the rest of the UI.

**Comment by supertylerc** [comment]
I've rewritten the UI for the migration page and updated the JavaScript.  It just needs to be tested to ensure its interaction with the API still works as expected.  Screenshot below.

![new-migration-page](https://cloud.githubusercontent.com/assets/4076147/12043849/fe5576f8-ae3d-11e5-8be3-8615b03fe112.PNG)

**Comment by ytti** [comment]
Looks good to me.
