### ISSUE TITLE
Link for update broken, if you use a group

### ISSUE THREAD

**Issue by fhibler** [ytti/oxidized-web#6]
Demo URL:
http://1.1.1.1:8888/node/next/$group/$device (e.g. http://1.1.1.1:8888/node/next/edge/edgeswitch1)
shows Sinatra error (not found).

URL without group works:
http://1.1.1.1:8888/node/next/$device (e.g. http://1.1.1.1:8888/node/next/edgeswitch1)

**Comment by darkounet** [comment]
:up: 

We have the same problem, tried the @fhibler PR #7  and it WORKS fine !! :+1:

It is possible to accept the PR ?

Thx

**Comment by ytti** [comment]
Sorry this was my confusion, I somehow thought this was already merged. It's merged now.
