### ISSUE TITLE
Lock down web access?

### ISSUE THREAD

**Issue by tylerapplebaum** [ytti/oxidized-web#85]
How do I lock down this page? I don't want any random internal user to be able to pull of these device configs. Really, I only need to access the configs through the LibreNMS page (which is working great by the way!)

![image](https://cloud.githubusercontent.com/assets/8419153/12212735/787d642c-b622-11e5-8287-3577a080ca3f.png)

**Comment by ytti** [comment]
Sorry, I have no idea what is going on here.

If LibreNMS is fetching configs through Oxidized API, then wouldn't it be sufficient that you create some nftables rule to only allow LibreNMS machine to connect?

I guess you can't just shutdown the webinterface of Oxidized, if LibreNMS uses it. 

What do you think how this should work? What is your expectations? How do you think LibreNMS should be able to access Oxidized but some other user not?

**Comment by masonke** [comment]
I was running across this also. Is there a way to put some authentication on the page, even if it used the unix accounts on the box, or a local file?
~KEM

**Comment by ytti** [comment]
Does LibreNMS support providing access credentials towards Oxidized?

Please excuse my ignorance, I've not used LibreNMS. Currently I imagene LibreNMS integrates with Oxidized, uses its API to show configs of devices, this may be ways off. But under this assumption, we have to assume that the main thing to satisfy is that LibreNMS has to have access to Oxidized.

After we've satisfied that, we can figure out how to restrict others. But if LibreNMS cannot provide user credentials to access Oxidized, then I guess only thing you can do, is nftables rule.

Of course you can always have Oxidized listen to 127.0.0.1 and expose it via another httpd in any manner you want, with any authentication you want.

**Comment by laf** [comment]
LibreNMS connects directly to the API, if that used authentication built into the Oxidized WebUI then we'd struggle, if it was something like basic auth or passing an API key over then we can do that easily enough.

**Comment by masonke** [comment]
How about an option to disable the web page and only expose the api?
~KEM

**Comment by ytti** [comment]
Let's work on premise that API and web page are different things, they are not, but let's entertain that for a moment.

If we shutdown web page access, and only allow global API access. How have we made things better? Arbitrary user can still reach the API and get the data.

If my suggestion of nftables (iptables for the guys's rocking to 80's) is not acceptable (why not), and if my suggestion of using overlay webserver for access control is not acceptable (why not ), then I think http basic auth is something we could do.

**Comment by supertylerc** [comment]
@masonke, this isn't currently possible. Even if it were, a user could just as easily curl the configs to get them. 

@laf, I don't think that token authentication is built into oxidized-web yet. I think the current practice is to proxy using nginx, Apache, or the like and handle authentication there as @ytti mentioned. This would let you use HTTP basic auth. 

That's probably a "good enough" solution for the moment: as @ytti said, have oxidized-web listen only on 127.0.01, proxy with Apache or nginx (or similar), enable basic auth, and it sounds like (correct me if I'm wrong, @laf) LibreNMS could use that. 

Would that satisfy requirements, @masonke and @tylerapplebaum?

**Comment by masonke** [comment]
Sounds good to me
~KEM

**Comment by tylerapplebaum** [comment]
Absolutely. Thanks guys!

**Comment by supertylerc** [comment]
@masonke, @tylerapplebaum, and @laf, I'm going to close this as it sounds like the solutions presented herein are acceptable.  Please reopen if your concerns are not addressed.

**Comment by jarora11** [comment]
@ytti @supertylerc Am not sure about this hence asking, what if we want to protect the API (don't really care about the web interface as much). But I would prefer to have either token based auth or ldap based auth against the API. Any way to implement that?

**Comment by laf** [comment]
At present it's not supported so would need someone to add that core support into it.

LDAP support doesn't seem sane as that just opens up people wanting to add AD, MySQL, Radius, etc, etc. Implementing basic auth or a token system seems the most logical way forward.

**Comment by jarora11** [comment]
@laf thanks for the prompt response. Lets ignore LDAP then. But how much effort would it be to add basic token based auth? Unfortunately am not Ruby savy, if this was written in Python I would have gladly offered support to add it myself.

**Comment by laf** [comment]
You're at the mercy of someone who wants that support to right the code :(
