### ISSUE TITLE
Query Supported Models

### ISSUE THREAD

**Issue by justinjahn** [ytti/oxidized-web#87]
Is there a way to query for a list of available models?  I'm working on a web-based way to manage the node list, and it would be great if one could validate the model before adding it to the database.

Thanks!

**Comment by ytti** [comment]
This is currently not possible. We load the models runtime based on which models are needed. 

I'm open to including API which iterates model directories and returns models. But won't do it myself.

**Comment by justinjahn** [comment]
Fair enough.  I'll look into it, and see if I can help.
