### ISSUE TITLE
Reload api does not work

### ISSUE THREAD

**Issue by stefanplug** [ytti/oxidized-web#88]
oxidized (0.10.0, 0.4.1)
oxidized-script (0.1.1)
oxidized-web (0.6.1, 0.6.0)

When I run:
curl http://localhost:8888/reload
I get:
Errno::ENOENT: No such file or directory - /home/oxidized/.gem/ruby/gems/oxidized-web-0.6.1/lib/oxidized/web/views/default.haml
This file indeed does not exist.

full error:
Errno::ENOENT: No such file or directory - /home/oxidized/.gem/ruby/gems/oxidized-web-0.6.1/lib/oxidized/web/views/default.haml
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt/template.rb:219:in `initialize'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt/template.rb:219:in `open'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt/template.rb:219:in `read_template_file'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt/template.rb:78:in `block in initialize'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt/template.rb:79:in `call'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt/template.rb:79:in `initialize'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:861:in `new'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:861:in `block in compile_template'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt.rb:104:in `block in fetch'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt.rb:103:in `fetch'
        /home/oxidized/.gem/ruby/gems/tilt-2.0.2/lib/tilt.rb:103:in `fetch'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:840:in `compile_template'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:821:in `render'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:676:in `haml'
        /home/oxidized/.gem/ruby/gems/oxidized-web-0.6.1/lib/oxidized/web/webapp.rb:235:in `out'
        /home/oxidized/.gem/ruby/gems/oxidized-web-0.6.1/lib/oxidized/web/webapp.rb:73:in `block in <class:WebApp>'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /home/oxidized/.gem/ruby/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/oxidized/.gem/ruby/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/oxidized/.gem/ruby/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /home/oxidized/.gem/ruby/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/oxidized/.gem/ruby/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /home/oxidized/.gem/ruby/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call
        /home/oxidized/.gem/ruby/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
        /home/oxidized/.gem/ruby/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /home/oxidized/.gem/ruby/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /home/oxidized/.gem/ruby/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
        /home/oxidized/.gem/ruby/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
        /home/oxidized/.gem/ruby/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
        /home/oxidized/.gem/ruby/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
        /home/oxidized/.gem/ruby/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
        /home/oxidized/.gem/ruby/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
        /home/oxidized/.gem/ruby/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
        /home/oxidized/.gem/ruby/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
        /home/oxidized/.gem/ruby/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'

Other API calls such as getting a host's configuration works fine.

When querying a obviously non existent API call I get a non-existent answer
curl http://localhost:8888/foo
<!DOCTYPE html>
<html>
....
  <h2>Sinatra doesn&rsquo;t know this ditty.</h2>
....
</html>

When querying a non-existent, but similar API call then I get the same as with reload:

curl http://localhost:8888/reloadje
Errno::ENOENT: No such file or directory - /home/oxidized/.gem/ruby/gems/oxidized-web-0.6.1/lib/oxidized/web/views/default.haml
....

**Comment by ytti** [comment]
391481afd7be broken this @supertylerc was this intentional, i.e. should we return something else on 'reload'?

**Comment by mikebryant** [comment]
As a workaround, you can do `curl 'http://localhost:8888/reload?format=json'`

**Comment by stefanplug** [comment]
Workaround works, many thanks!

**Comment by supertylerc** [comment]
Apologies for missing this. There's not a link to it that I can find from the web interface, thus it is sort of "hidden." I suspect it is similar to the /stats route that I also fixed and added a link for. 

I think this is the only thing that references default.haml. Nothing else did, which is why it was removed. I'll fix this in the next day or two. I'll also add a link to reload via the web UI.

**Comment by ytti** [comment]
No worries, impossible to clean stuff without breaking stuff. Or at least exponentially more expensive to approach 100%.

**Comment by supertylerc** [comment]
Very busy the past few days, so this slipped by me.  I'm working on it now and should have a fix merged by the end of tonight.

**Comment by supertylerc** [comment]
@stefanplug @mikebryant @ytti see #90 for a fix.  Ultimately, I plan on making the "reload" API reachable from within the Web UI as well.  This is a fix until I get to that (possibly this weekend).

I'll merge the PR tomorrow morning if there are no objections to the implementation (and if @ytti hasn't merged it by then).

**Comment by supertylerc** [comment]
#90 has been merged, which will fix the raised exception. You can cut a gem from master to have the fix.

**Comment by supertylerc** [comment]
Closing as #90 has been merged and #92 addresses the desired UI implementation.
