### ISSUE TITLE
Add button to reload node file in web gui

### ISSUE THREAD

**Issue by emjemj** [ytti/oxidized-web#92]
It would be nice to have a button in the web UI to re-read the node file (router.db or similar) in the web gui (call to /reload).

**Comment by ytti** [comment]
Yeah, it was there. I think @jalmargyyk's webrework accidentaly removed it. @supertylerc is readding it.

**Comment by supertylerc** [comment]
Yup! See #88 for a little background. Should be done some time this weekend.

**Comment by supertylerc** [comment]
I think I have this working, but I left my laptop (which has my full lab/testing setup on it) at work on Friday, so I can't really test until Monday night.  But I've pushed a branch to my fork that should implement this feature.  Once I can test it Monday night, I'll submit the PR.  Sorry for the delay!

**Comment by supertylerc** [comment]
Just tested this.  Opened #93 to implement it.
