### ISSUE TITLE
Live demo server not found

### ISSUE THREAD

**Issue by yudayyy** [ytti/oxidized-web#96]
I cannot access the live demo site.

**Comment by ytti** [comment]
@nopedial

**Comment by nopedial** [comment]
It's back from an hour or so but there are some troubles to pull data atm. I'll work on it in a few hours.

**Comment by supertylerc** [comment]
Looks like live demo is up and available.  Closing issue.  Please reopen if you disagree or feel there is something else needed.

**Comment by malkovitch** [comment]
Hello,

The live demo website is down again.

Error : 502 Bad gateway
