### ISSUE TITLE
Web Layout

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized-web#98]
Is there something wrong with the current layout? This is the way the site appears in Firefox and Chrome.

https://i.imgur.com/38br7wi.png

Not sure if this is on purpose or just some CSS that needs cleaned up.  The old web ui had margins on the left and right, etc.

**Comment by supertylerc** [comment]
I'm not concerned about the margins.  That said, I'm not a designer, so if there are design reasons to have margins, let's get them in place.

The logo looks like it's just a bug in CSS.  Lining it up with the `Stats` and `Migration` links should happen whenever its CSS is fixed.

**Comment by etern4ever** [comment]
In the end, its just an interface to configuration files.  But I am just comparing it to the old interface. Which had margins, logo in header didn't cross the line, etc.

**Comment by supertylerc** [comment]
Thanks for the feedback. There's another issue that is a little more pressing than this, but this should be low-hanging fruit to fix.

**Comment by supertylerc** [comment]
#100 seems to have aimed to fix this, but I still see that the logo is not placed very well.  I discovered that 8 days ago someone else fixed the bug that I also fixed tonight, so I'll start working on this as well.

**Comment by supertylerc** [comment]
@etern4ever this should be fixed by #101, which I've just merged.  It now looks like this:

<img width="879" alt="screenshot 2016-05-04 19 49 56" src="https://cloud.githubusercontent.com/assets/4076147/15035040/a96456fc-1231-11e6-92a6-c2e5c980e167.png">

**Comment by etern4ever** [comment]
@supertylerc Much better.  Thanks!
